# Generated by Django 4.1.2 on 2022-11-17 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0002_alter_director_image_alter_movie_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='video_url',
            field=models.CharField(max_length=400, null=True),
        ),
    ]
